<?php

namespace Administrator\Administration\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * rechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rechercheRepository extends EntityRepository
{
}
